### PR TITLE
handle merge conflicts

### PR DESCRIPTION
**Pull request by MaesterChestnut**
Hoping that getting this branch resynced up with master might speed the process of getting the emitevents change merged

### CODE REVIEW

**Comment by nikolaymihaylov** [comment]
Hey, thanks for your effort and for your suggestion! I think we should actually exclude the build files since these might be one reason why https://github.com/jeromeetienne/AR.js/pull/303 doesn't get merged.

I actually created a new branch called `20180619-update-dev` where I merged the latest `jeromeetienne/AR.js/dev` (as of 2018-06-19) into it. This excludes the build files and moves the CHANGELOG info up, not tied to a specific version. Other than that your `mergeBranch` seemed to be pretty similar to my `20180619-update-dev` so that's good. You could apply those additional small changes to your `mergeBranch` or we can proceed with my `20180619-update-dev`, up to you. (I'll be sure to reference you in the original PR).

However, when I was testing the updated example, it seems that the `.emit()` doesn't work anymore for some reason:
```
_this.el.emit('markerFound')
```
Or then the other possibility is that this no longer works:
```
marker.addEventListener('markerFound', function() {
```

Did you encounter the same problem?

**Comment by MaesterChestnut** [comment]
@nikolaymihaylov yea, I've had similar issues. Using the version you had before the update works fine.  Could it possibly be an issue with the minified version conflicting with the nonminified version? 🤔

**Comment by MaesterChestnut** [comment]
@nikolaymihaylov looks like there was a left over merge issue on my branch; removed the extra characters and pushed up again. You should see the events working when you point to https://raw.githubusercontent.com/MaesterChestnut/AR.js/mergeBranch/aframe/build/aframe-ar.js
like I'm doing here: https://github.com/MaesterChestnut/ar-business-card/blob/master/index.html#L4

**Comment by nikolaymihaylov** [comment]
Hey @MaesterChestnut and thanks for your effort! I'll try to take a look today or tomorrow and hopefully merge this pull request.

**Comment by nikolaymihaylov** [comment]
Hello @MaesterChestnut, I ended up making the changes myself due to the following reasons:
- I wanted to exclude the build file changes altogether.
- I wanted to make the `CHANGELOG` so that the changes in my pull request are not associated with a specific version. The maintainers of `AR.js` will probably give it a version number if they decide to merge the changes.

I did mention you though in the original pull request to give you credit for your effort. Thank you! I hope it will get merged to the original repository soon.

**Pull request closed without merging**
